version: "3.4"

services:
  web: 
    build:
      context: ./
      network: host
    links: mongo
    ports:
      - '8000:5000'
    
  mongo:
    image: mongo:5.0
    restart: always
    volumes:
      - 'mongo:/data/db'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root


volumes:
  mongo: {}
