version: "3.4"

services:
  web: 
    build:
      context: .
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    network_mode: host
    ports:
      - '8000:5000'
    
  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - '27017'
    volumes:
      - 'mongo:/data/db'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=S3cret

volumes:
  mongo: {}
