name: Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  execute:
    timeout-minutes: 1 #this should be enough to start, the bot itself detaches afterwards
    runs-on:
      labels: self-hosted 
    steps:
      - uses: actions/checkout@v2
      
      - name: apt install
        run: apt install gcc -y

      - name: compose up
        run: docker-compose up --build -d
